services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 04Rex-Website
    ports:
      - "8080:80"
    restart: unless-stopped
    
    healthcheck:
      # Use wget to check if the homepage returns a 200 OK
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s    # How often to check
      timeout: 5s      # How long to wait for a response
      retries: 3       # Number of failures before marking as "unhealthy"
      start_period: 5s # Give Nginx a few seconds to boot up before checking